services:
  ftp-server:
    environment:
      - USERS=foo|pass
      - ADDRESS=localhost
    image: delfer/alpine-ftp-server
    network_mode: host
    volumes:
      - './data:/ftp/foo'
  db-server:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql